env: development

http_server:
  host: "localhost"
  port: "8081"
  read_header_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s

database:
  host: "localhost"
  port: "5433"
  username: "postgres"
  db_name: "hookah_notifications"
  ssl_mode: "disable"

kafka:
  brokers:
    - "localhost:9092"
  group_id: "notification-service"
  required_acks: -1
  async: false

mailgun:
  from: "support@sandbox01b70f53b1714b2a88faa250ebbcc234.mailgun.org"